### ISSUE TITLE
Mongoose.createConnection

### ISSUE THREAD

**Issue by dcolens** [disjunction/node-cache-manager-mongoose#2]
thanks for the project it looks great. I am wondering how I can pass a mongoose connection obtained from mongoose.createConnection, in my use cases I have multiple connections to different databases and I use mongoose.createConnection instead of mongoose.connect, passing the result of mongoose.createConnection breaks cache-manager-mongoose. 

Is this possible ?

**Comment by disjunction** [comment]
Hi, thanks for spotting this problem. I'll make an extra option "connection" for this case (hopefully today).

**Comment by disjunction** [comment]
it's now available on npm, version 0.0.3
