### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by keyndark** [disjunction/node-cache-manager-mongoose#6]
```
(node:24331) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RangeError: Maximum call stack size exceeded
(node:24331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by disjunction** [comment]
please provide the code snippet

**Comment by keyndark** [comment]
Sorry. For now we can close issue.  I found workaround. 

I`m trying to save in cache object with five keys and data string with around 300kb in each. Now im save string with JSON.stringify and when get from cache JSON.parse. This method pretty fast for me.

Thanks for reply.
